services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3001'
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DB_HOST=mypg_db
      - DB_PORT=5432
      - DB_PASSWORD=12131415
      - DB_USERNAME=postgres
      - DB_NAME=my-nest-project
    volumes:
      - ./src:/usr/src/app/src
  mypg_db:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: 12131415
      POSTGRES_USER: postgres
      POSTGRES_DB: my-nest-project
